# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('colour', models.CharField(default='495057', max_length=6)),
                ('by_line', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('site', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='blogconfiguration',
            name='social_links',
            field=models.ManyToManyField(blank=True, null=True, to='configuration.SocialLink'),
        ),
    ]
