# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogconfiguration',
            name='social_links',
            field=models.ManyToManyField(blank=True, to='configuration.SocialLink'),
        ),
    ]
