# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 01:16
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings
from django.contrib.auth.hashers import make_password


def create_admin_user(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    admin, created = User.objects.get_or_create(username='admin', email='admin@example.com')
    if created:
        admin.password = make_password('asdf0987')
        admin.is_superuser = True
        admin.is_staff = True
        admin.save()


def remove_admin_user(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20170708_0132'),
    ]

    operations = [
        migrations.RunPython(create_admin_user, remove_admin_user),
    ]
