# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_auto_20170710_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogconfiguration',
            name='google_analytics',
            field=models.CharField(blank=True, default='', help_text='Full Google Analytics code', max_length=20),
        ),
    ]
